FROM maven:latest

# set working directory
WORKDIR /app

# Copy project file
COPY pom.xml ./

# install dependencies
RUN mvn dependency:go-offline

# copy all project
COPY . .

# compile source code
RUN mvn javadoc:javadoc 
